app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('', views.IndexView.as_view(),name='index'),
    path('list/', views.ListView.as_view(),name='list'), # 类视图的路径
    path('detail/<int:id>/', views.DetailView.as_view(),name='detail'),
    path('category/<int:id>/', views.CategoryView.as_view(),name='category'),
    path('tag/<int:id>/', views.TagView.as_view(),name='tag'),
    path('search/', views.SearchView.as_view(),name='search'),
    path('login/', views.LoginView.as_view(),name='login'),
    path('register/', views.RegisterView.as_view(),name='register'),
    path('logout/', views.log_out,name='logout'),
    path('comment/', views.comment,name='comment'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.views.static import serve

from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('app.urls','app'),namespace='app')),
    path('ueditor/', include('DjangoUeditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from DjangoUeditor.models import UEditorField
# Create your models here.


class BlogUser(AbstractUser):
    phone = models.CharField(verbose_name='手机号',max_length=11)

class BaseModel(models.Model):

    is_delete = models.BooleanField(verbose_name='是否删除',default=False)
    created_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    updated_time = models.DateTimeField(verbose_name='更新时间', auto_now=True)
    class Meta:
        abstract = True

#分类
class Category(BaseModel):
    name = models.CharField(verbose_name='分类',max_length=10)
    position = models.IntegerField(verbose_name='排序',default=0)

    class Meta:
        ordering = ['position']
        verbose_name = '分类'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name
#标签
class Tag(BaseModel):
    name = models.CharField(verbose_name='标签',max_length=10)
    position = models.IntegerField(verbose_name='排序',default=0)
    class Meta:
        ordering = ['position']
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

#轮播图
class Banner(BaseModel):
    title = models.CharField(verbose_name='标题',max_length=10)
    cover = models.ImageField(verbose_name='图片',upload_to='banner/%Y/%m/%d')
    link = models.URLField(verbose_name='跳转地址')
    position = models.IntegerField(verbose_name='排序',default=0)

    class Meta:
        ordering = ['position']
        verbose_name = '轮播图'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

# 文章
class Article(BaseModel):
    title = models.CharField(verbose_name='标题',max_length=100)
    intro = models.CharField(verbose_name='简介',max_length=255)
    vnum = models.IntegerField(verbose_name='浏览量',default=0)
    cover = models.ImageField(verbose_name='图片',upload_to='article/%Y/%m/%d')
    is_top = models.BooleanField(verbose_name='是否置顶',default=False)
    content = UEditorField(width=600,height=300,toolbars='full',imagePath
    ="article/content/%(basename)s_%(datetime)s.%(extname)s",filePath='files/')

    user = models.ForeignKey(to=BlogUser,on_delete=models.CASCADE)
    category = models.ForeignKey(to=Category,on_delete=models.CASCADE)
    tag = models.ManyToManyField(to=Tag)

    class Meta:
        ordering = ['-created_time']
        verbose_name = '文章'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title

# 评论表
class Comment(BaseModel):
    content = models.CharField(verbose_name='评论内容',max_length=255)
    users = models.ForeignKey(to=BlogUser,on_delete=models.CASCADE)
    article = models.ForeignKey(to=Article,on_delete=models.CASCADE)

    class Meta:
        ordering = ['-created_time']
        verbose_name = '评论'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content

# 友情链接表
class FriendLink(BaseModel):
    name = models.CharField(verbose_name='友情链接',max_length=255)
    link = models.URLField(verbose_name='跳转地址')
    position = models.IntegerField(verbose_name='排序',default=0)

    class Meta:
        ordering = ['position']
        verbose_name = '友情链接'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

templates/101.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
我是101.html
</body>
</html>

templates/_pagination.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load i18n %}
<div class="pagination">
    {% if all_article.has_previous %}
        <a href="?{{ all_article.previous_page_number.querystring }}"
           class="prev">上一页</a>
    {% else %}
        <span class="disabled prev">上一页 </span>
    {% endif %}
    {% for page in all_article.pages %}
        {% if page %}
            {% ifequal page all_article.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if all_article.has_next %}
        <a href="?{{ all_article.next_page_number.querystring }}" class="next">下一页</a>
    {% else %}
        <span class="disabled next">下一页</span>
    {% endif %}
</div>
</body>
</html>

templates/base.html
<!doctype html>
{% load staticfiles %}
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}{% endblock %}</title>
<meta name="keywords" content="">
<meta name="description" content="">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/nprogress.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'images/icon.png' %}">
<link rel="shortcut icon" href="{% static 'images/favicon.ico' %}">
<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'js/nprogress.js' %}"></script>
<script src="{% static 'js/jquery.lazyload.min.js' %}"></script>
<!--[if gte IE 9]>
  <script src="js/jquery-1.11.1.min.js" type="text/javascript"></script>
  <script src="js/html5shiv.min.js" type="text/javascript"></script>
  <script src="js/respond.min.js" type="text/javascript"></script>
  <script src="js/selectivizr-min.js" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
  <script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>
<body class="user-select {% block  single%}{% endblock %}">
<header class="header">
<nav class="navbar navbar-default" id="navbar">
<div class="container">
  <div class="header-topbar hidden-xs link-border">
	<ul class="site-nav topmenu">
	  <li><a href="#" >标签云</a></li>
		<li><a href="#" rel="nofollow" >读者墙</a></li>
		<li><a href="#" title="RSS订阅" >
			<i class="fa fa-rss">
			</i> RSS订阅
		</a></li>
	</ul>
			 勤记录 懂分享</div>
  <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false"> <span class="sr-only"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
	<h1 class="logo hvr-bounce-in"><a href="#" title="木庄网络博客"><img src="{% static 'images/201610171329086541.png' %}" alt="木庄网络博客"></a></h1>
  </div>
  <div class="collapse navbar-collapse" id="header-navbar">
	<form class="navbar-form visible-xs" action="/Search" method="post">
	  <div class="input-group">
		<input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
	<ul class="nav navbar-nav navbar-left">
	  <li><a data-cont="木庄网络博客" title="木庄网络博客" href="{% url 'app:index' %}">首页</a></li>
	  <li><a data-cont="列表页" title="列表页" href="{% url 'app:list' %}">列表页</a></li>
	</ul>
      <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
              <li><a data-cont="{{ request.user.username }}" title="{{ request.user.username }}" >欢迎您：{{ request.user.username }}</a></li>
              <li><a data-cont="列表页" title="列表页" href="{% url 'app:logout' %}">退出</a></li>
          {% else %}
               <li><a data-cont="木庄网络博客" title="木庄网络博客" href="{% url 'app:login' %}">登录</a></li>
              <li><a data-cont="列表页" title="列表页" href="{% url 'app:register' %}">注册</a></li>
          {% endif %}
	</ul>
  </div>
</div>
</nav>
    {% block style %}{% endblock %}
</header>
{% block content %}{% endblock %}
<footer class="footer">
<div class="container">
<p>Copyright &copy; 2016.Company name All rights reserved.<a target="_blank" href="http://sc.chinaz.com/moban/">&#x7F51;&#x9875;&#x6A21;&#x677F;</a></p>
</div>
<div id="gotop"><a class="gotop"></a></div>
</footer>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{#<script src="{% static 'js/jquery.ias.js' %}"></script>#}
<script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %}贾松{% endblock %}
{% block content %}
<section class="container">
<div class="content-wrap">
<div class="content">
  <div id="focusslide" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
        {% for banner in banners %}
            {% if forloop.counter0 == 0 %}
                <li data-target="#focusslide" data-slide-to="{{forloop.counter0}}" class="active"></li>
            {% else %}
                <li data-target="#focusslide" data-slide-to="{{forloop.counter0}}"></li>
            {% endif %}
        {% endfor %}
	</ol>
	<div class="carousel-inner" role="listbox">
        {% for banner in banners %}
            {% if forloop.counter0 == 0 %}
              <div class="item active">
              <a href="{{banner.link}}" target="_blank" title="{{banner.title}}" >
              <img src="{{MEDIA_URL}}{{ banner.cover }}" alt="{{banner.title}}" class="img-responsive"></a>
              </div>
            {% else %}
              <div class="item">
              <a href="{{banner.link}}" target="_blank" title="{{banner.title}}" >
              <img src="{{MEDIA_URL}}{{ banner.cover }}" alt="{{banner.title}}" class="img-responsive"></a>
              </div>
            {% endif %}
        {% endfor %}

	</div>
	<a class="left carousel-control" href="#focusslide" role="button" data-slide="prev" rel="nofollow"> <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <span class="sr-only">上一个</span> </a> <a class="right carousel-control" href="#focusslide" role="button" data-slide="next" rel="nofollow"> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> <span class="sr-only">下一个</span> </a> </div>
  {% for article in top_article %}
    <article class="excerpt-minic excerpt-minic-index">
		<h2><span class="red">【推荐】</span><a target="_blank" href="{% url 'app:detail' id=article.id %}" title="{{ article.title }}" >{{ article.title }}</a>
		</h2>
		<p class="note">{{ article.intro }}</p>
	</article>
    {% endfor %}
  <div class="title">
	<h3>最新发布</h3>
	<div class="more">
        {% for cat in cats %}
			<a href="{% url 'app:category' id=cat.id %}" title="{{cat.name}}" >{{cat.name}}</a>
        {% endfor %}
		</div>
  </div>
{% for article in all_article %}
  <article class="excerpt " style="">

  <a class="focus" href="{% url 'app:detail' id=article.id %}" title="{{article.title}}" target="_blank" ><img class="thumb" data-original="{{MEDIA_URL}}{{ article.cover }}" src="{{MEDIA_URL}}{{ article.cover }}" alt="{{article.title}}"  style="display: inline;"></a>
		<header><a class="cat" href="{% url 'app:detail' id=article.id %}" title="{{ article.category.name }}" >{{ article.category.name }}<i></i></a>
			<h2><a href="{% url 'app:detail' id=article.id %}" title="{{article.title}}" target="_blank" >{{article.title}}</a>
			</h2>
		</header>
		<p class="meta">
			<time class="time"><i class="glyphicon glyphicon-time"></i> {{article.created_time|date:'Y-m-d'}}</time>
			<span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{article.vnum}}</span> <a class="comment" href="{% url 'app:detail' id=article.id %}" title="评论" target="_blank" ><i class="glyphicon glyphicon-comment"></i> {{article.comment_set.count}}</a>
		</p>
		<p class="note">{{ article.intro }}</p>
	</article>
{% endfor %}
  <nav class="pagination" style="display: none;">
	<ul>
	  <li class="prev-page"></li>
	  <li class="active"><span>1</span></li>
	  <li><a href="?page=2">2</a></li>
	  <li class="next-page"><a href="?page=2">下一页</a></li>
	  <li><span>共 2 页</span></li>
	</ul>
  </nav>
</div>
</div>
<aside class="sidebar">
<div class="fixed">
  <div class="widget widget-tabs">
	<ul class="nav nav-tabs" role="tablist">
	  <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab" data-toggle="tab" >统计信息</a></li>
	  <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab" >联系站长</a></li>
	</ul>
	<div class="tab-content">
	  <div role="tabpanel" class="tab-pane contact active" id="notice">
		<h2>日志总数:
			  {{count}}篇
		  </h2>
		  <h2>网站运行:
		  <span id="sitetime">88天 </span></h2>
	  </div>
		<div role="tabpanel" class="tab-pane contact" id="contact">
		  <h2>QQ:
			  <a href="" target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom" title=""  data-original-title="QQ:"></a>
		  </h2>
		  <h2>Email:
		  <a href="#" target="_blank" data-toggle="tooltip" rel="nofollow" data-placement="bottom" title=""  data-original-title="#"></a></h2>
	  </div>
	</div>
  </div>
  <div class="widget widget_search">
	<form class="navbar-form" action="{% url 'app:search' %}" method="get">
	  <div class="input-group">
		<input type="text" name="kw" class="form-control" size="35" placeholder="请输入关键字" maxlength="15" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
  </div>
</div>
<div class="widget widget_hot">
	  <h3>最新评论文章</h3>
	  <ul>
          {% for commet in new_commets %}
			<li><a title="{{commet.article.title}}" href="{% url 'app:detail' id=commet.article.id %}" ><span class="thumbnail">
				<img class="thumb" data-original="{{ MEDIA_URL }}{{ commet.article.cover }}" src="{{ MEDIA_URL }}{{ commet.article.cover }}" alt="{{commet.article.title}}"  style="display: block;">
			</span><span class="text">{{commet.article.title}}</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
				{{commet.article.created_time|date:'Y-m-d'}}
			</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>{{commet.article.vnum}}</span></a></li>
          {% endfor %}
	  </ul>
 </div>
 <div class="widget widget_sentence">    
	<a href="#" target="_blank" rel="nofollow" title="专业网站建设" >
	<img style="width: 100%" src="/static/images/201610241224221511.jpg" alt="专业网站建设" ></a>
 </div>
 <div class="widget widget_sentence">    
	<a href="#" target="_blank" rel="nofollow" title="MZ-NetBlog主题" >
	<img style="width: 100%" src="/static/images/ad.jpg" alt="MZ-NetBlog主题" ></a>
 </div>
<div class="widget widget_sentence">
  <h3>友情链接</h3>

      <div class="widget-sentence-link">
          {% for fk in fks %}
              <a href="{{fk.link}}" title="{{fk.name}}" target="_blank" >{{fk.name}}</a>&nbsp;&nbsp;&nbsp;
          {% endfor %}
      </div>

</div>
</aside>
</section>
    <script>
        var sdate = new Date('2020-03-10');
        var edate = new Date();
        var days = edate.getTime() - sdate.getTime();
        var time = parseInt(days/(1000*60*60*24));
        sitetime  = window.document.getElementById('sitetime');
        sitetime.innerHTML = time + '天'
    </script>
{% endblock %}

templates/list.html
{% extends 'base.html' %}
{% block title %}list{% endblock %}
{% block content %}
<section class="container">
<div class="content-wrap">
<div class="content">
  <div class="title">
	<h3 style="line-height: 1.3">所有文章</h3>
  </div>
{% for article in all_article.object_list %}
  <article class="excerpt " style="">
  <a class="focus" href="{% url 'app:detail' id=article.id %}" title="{{article.title}}" target="_blank" ><img class="thumb" data-original="{{MEDIA_URL}}{{ article.cover }}" src="{{MEDIA_URL}}{{ article.cover }}" alt="{{article.title}}"  style="display: inline;"></a>
		<header><a class="cat" href="#" title="{{ article.category.name }}" >{{ article.category.name }}<i></i></a>
			<h2><a href="{% url 'app:detail' id=article.id %}" title="{{article.title}}" target="_blank" >{{article.title}}</a>
			</h2>
		</header>
		<p class="meta">
			<time class="time"><i class="glyphicon glyphicon-time"></i> {{article.created_time|date:'Y-m-d'}}</time>
			<span class="views"><i class="glyphicon glyphicon-eye-open"></i> {{article.vnum}}</span> <a class="comment" href="{% url 'app:detail' id=article.id %}" title="评论" target="_blank" ><i class="glyphicon glyphicon-comment"></i> {{article.comment_set.count}}</a>
		</p>
		<p class="note">{{ article.intro }}</p>
	</article>
{% endfor %}



{% include '_pagination.html' %}
  <nav class="pagination" style="display: none;">
	<ul>
	  <li class="prev-page"></li>
	  <li class="active"><span>1</span></li>
	  <li><a href="?page=2">2</a></li>
	  <li class="next-page"><a href="?page=2">下一页</a></li>
	  <li><span>共 2 页</span></li>
	</ul>
  </nav>
</div>
</div>
<aside class="sidebar">
<div class="fixed">
  <div class="widget widget_search">
	<form class="navbar-form" action="{% url 'app:search' %}" method="get">
	  <div class="input-group">
		<input type="text" name="kw" class="form-control" size="35" placeholder="请输入关键字" maxlength="15" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
  </div>
  <div class="widget widget_sentence">
	<h3>标签云</h3>
	<div class="widget-sentence-content">
		<ul class="plinks ptags">
            {% for tag in tags %}
			<li><a href="{% url 'app:tag' id=tag.id %}" title="{{tag.name}}" draggable="false">{{tag.name}} <span class="badge">{{ tag.article_set.count }}</span></a></li>
			{% endfor %}
		</ul>
	</div>
  </div>
</div>
<div class="widget widget_hot">
	  <h3>最新评论文章</h3>
	  <ul>
          {% for commet in new_commets %}
			<li><a title="{{commet.article.title}}" href="{% url 'app:detail' id=commet.article.id %}" ><span class="thumbnail">
				<img class="thumb" data-original="{{ MEDIA_URL }}{{ commet.article.cover }}" src="{{ MEDIA_URL }}{{ commet.article.cover }}" alt="{{commet.article.title}}"  style="display: block;">
			</span><span class="text">{{commet.article.title}}</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
				{{commet.article.created_time|date:'Y-m-d'}}
			</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>{{commet.article.vnum}}</span></a></li>
          {% endfor %}
	  </ul>
  </div>
  <div class="widget widget_sentence">

<a href="#" target="_blank" rel="nofollow" title="MZ-NetBlog主题" >
	<img style="width: 100%" src="/static/images/ad.jpg" alt="MZ-NetBlog主题" ></a>

</div>
  <div class="widget widget_sentence">

<a href="#" target="_blank" rel="nofollow" title="专业网站建设" >
	<img style="width: 100%" src="/static/images/201610241224221511.jpg" alt="专业网站建设" ></a>

</div>
</aside>
</section>
{% endblock %}

templates/show.html
{% extends 'base.html' %}
{% block title %}show{% endblock %}
{% block  single%}single{% endblock %}
{% block content %}
<section class="container">
<div class="content-wrap">
<div class="content">
  <header class="article-header">
	<h1 class="article-title"><a href="#" title="{{article.title}}" >{{article.title}}</a></h1>
	<div class="article-meta"> <span class="item article-meta-time">
	  <time class="time" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="发表时间：{{article.created_time|date:'Y-m-d'}}"><i class="glyphicon glyphicon-time"></i> {{article.created_time|date:'Y-m-d'}}</time>
	  </span> <span class="item article-meta-source" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="来源：{{article.user.username}}"><i class="glyphicon glyphicon-globe"></i> {{article.user.username}}</span> <span class="item article-meta-category" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{article.category.name}}"><i class="glyphicon glyphicon-list"></i> <a href="#" title="{{article.category.name}}" >{{article.category.name}}</a></span> <span class="item article-meta-views" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="浏览量：{{article.vnum}}"><i class="glyphicon glyphicon-eye-open"></i> {{article.vnum}}</span> <span class="item article-meta-comment" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="评论量"><i class="glyphicon glyphicon-comment"></i> {{article.comment_set.count}}</span> </div>
  </header>
  <article class="article-content">
    {{ article.content|safe }}
  </article>
  <div class="article-tags">标签：
      {% for tag in article.tag.all %}
      <a href="{% url 'app:tag' id=tag.id %}" rel="tag" >{{tag.name}}</a>
      {% endfor %}
  </div>
  <div class="relates">
	<div class="title">
	  <h3>相关推荐</h3>
	</div>
	<ul>
        {% for art in recommend_articles %}
            {% if art.id != article.id %}
	            <li><a href="{% url 'app:detail' id=art.id %}" title="" >{{art.title}}</a></li>
            {% else %}
            {% endif %}
        {% endfor %}
	</ul>
  </div>
  <div class="title" id="comment">
	<h3>评论</h3>
  </div>
  <div id="respond">
		<form id="comment-form" name="" action="{% url 'app:comment' %}" method="POST">
            {% csrf_token %}
			<div class="comment">
				<div class="comment-box">
					<textarea placeholder="您的评论或留言（必填）" name="content" id="comment-textarea" cols="100%" rows="3" tabindex="3"></textarea>
					<div class="comment-ctrl">
						<div class="comment-prompt" style="display: none;"> <i class="fa fa-spin fa-circle-o-notch"></i> <span class="comment-prompt-text">评论正在提交中...请稍后</span> </div>
						<div class="comment-success" style="display: none;"> <i class="fa fa-check"></i> <span class="comment-prompt-text">评论提交成功...</span> </div>
                        <input type="hidden" name="id" tabindex="4" value="{{ article.id }}">
                        <button type="submit" name="comment-submit" id="comment-submit" tabindex="4">评论</button>
					</div>
				</div>
			</div>
		</form>
		
	</div>
  <div id="postcomments">
	<ol id="comment_list" class="commentlist">
        {% for comment in comments %}
	<li class="comment-content"><span class="comment-f">#{{ forloop.revcounter }}</span><div class="comment-main"><p><a class="address" href="#" rel="nofollow" target="_blank">{{comment.users.username}}</a><span class="time">{{comment.created_time|date:'Y/m/d  h:m:s'}}</span><br>{{comment.content}}</p></div></li>
    {% endfor %}
    </ol>

  </div>
</div>
</div>
<aside class="sidebar">
<div class="fixed">
  <div class="widget widget-tabs">
	<ul class="nav nav-tabs" role="tablist">
	  <li role="presentation" class="active"><a href="#notice" aria-controls="notice" role="tab" data-toggle="tab" draggable="false">统计信息</a></li>
	  <li role="presentation"><a href="#contact" aria-controls="contact" role="tab" data-toggle="tab" draggable="false">联系站长</a></li>
	</ul>
	<div class="tab-content">
	  <div role="tabpanel" class="tab-pane contact active" id="notice">
		<h2>日志总数:
			  {{ count }}篇
		  </h2>
		  <h2>网站运行:
		  <span id="sitetime">88天 </span></h2>
	  </div>
		<div role="tabpanel" class="tab-pane contact" id="contact">
		  <h2>QQ:
			  <a href="" target="_blank" rel="nofollow" data-toggle="tooltip" data-placement="bottom" title="" draggable="false" data-original-title="QQ:577211782">577211782</a>
		  </h2>
		  <h2>Email:
		  <a href="mailto:577211782@qq.com" target="_blank" data-toggle="tooltip" rel="nofollow" data-placement="bottom" title="" draggable="false" data-original-title="Email:577211782@qq.com">577211782@qq.com</a></h2>
	  </div>
	</div>
  </div>
  <div class="widget widget_search">
	<form class="navbar-form" action="{% url 'app:search' %}" method="get">
	  <div class="input-group">
		<input type="text" name="kw" class="form-control" size="35" placeholder="请输入关键字" maxlength="15" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
  </div>
</div>
<div class="widget widget_hot">
	  <h3>最新评论文章</h3>
	  <ul>
          {% for commet in new_commets %}
			<li><a title="{{commet.article.title}}" href="{% url 'app:detail' id=commet.article.id %}" ><span class="thumbnail">
				<img class="thumb" data-original="{{ MEDIA_URL }}{{ commet.article.cover }}" src="{{ MEDIA_URL }}{{ commet.article.cover }}" alt="{{commet.article.title}}"  style="display: block;">
			</span><span class="text">{{commet.article.title}}</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
				{{commet.article.created_time|date:'Y-m-d'}}
			</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>{{commet.article.vnum}}</span></a></li>
          {% endfor %}
	  </ul>
  </div>
  <div class="widget widget_sentence">

<a href="#" target="_blank" rel="nofollow" title="MZ-NetBlog主题" >
	<img style="width: 100%" src="/static/images/ad.jpg" alt="MZ-NetBlog主题" ></a>

</div>
  <div class="widget widget_sentence">

<a href="#" target="_blank" rel="nofollow" title="专业网站建设" >
	<img style="width: 100%" src="/static/images/201610241224221511.jpg" alt="专业网站建设" ></a>

</div>
</aside>
</section>
    <script>
        var sdate = new Date('2020-03-10');
        var edate = new Date();
        var days = edate.getTime() - sdate.getTime();
        var time = parseInt(days/(1000*60*60*24));
        sitetime  = window.document.getElementById('sitetime');
        sitetime.innerHTML = time + '天'
    </script>
{% endblock %}